config/routes.rb
Avoberry::Application.routes.draw do

  resources :users do
    post  :reset, :on => :collection
    post  :new_post, :on => :member
    post  :comment_reply, :on => :member
    get   :show_form, :on => :member
  end
  
  resources :posts
  
  resources :friendships do
    post :create_request, :on => :collection
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :conversations do
    post :reply, :on => :member
    get :inbox, :on => :collection
    get :sent, :on => :collection
  end

  get '/contact' => 'pages#contact'
  get '/about' => 'pages#about'
  get '/help' => 'pages#help'
  get 'signup' => 'users#new'
  get '/signin' => 'sessions#new'
  get '/recover' => 'pages#recover'
  
  delete '/signout' => 'sessions#destroy'
  
  root :to => 'pages#home'

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  
  attr_accessible :subject, :c_sender_id, :c_recipient_id, :c_recipient2_id, :c_sender_del, 
                  :c_recipient_del
  
  has_many :msgs
  
  belongs_to :c_sender, :class_name => 'User'
  belongs_to :c_recipient, :class_name => 'User'
  
  before_create :set_count
  
  default_scope :order => 'conversations.created_at DESC'
  
  def update_count(user)
    num = 0
    msgs.each do |msg|
      num += 1 if (user == c_sender) and !msg.c_sender_read
      if (user == c_recipient) and !msg.c_recip_read
        num += 1
        num -= 1 if (user == c_sender) and !msg.c_sender_read
      end
    end
    self.count = num
    save
  end
  
  def all_read(user)
    msgs.each do |msg|
      if (user == c_sender) and !msg.c_sender_read
        msg.update_attributes(:c_sender_read => true)
      end
      if (user == c_recipient) and !msg.c_recip_read
        msg.update_attributes(:c_recip_read => true)
      end
    end
  end
  
  def create_msg(content, user)
    msg = Msg.new( :conversation_id => id,
                    :content => content,
                    :sender_id => user.id, 
                    :c_sender_read => true,
                    :c_recip_read => false)
    msg.save
  end
  
  def search_msgs(search)
    if search
      msgs.each do |msg|
        return true if !find(:all, :conditions => ['content LIKE ?', "%#{search}"]).empty?
      end
    else
      return false
    end
  end
  
  private
  
    def set_count
      self.count = 0
    end 
    
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  
  before_filter :check_change_password
  
  def index
    received_conversations = Conversation.find(:all, 
    :conditions => ["c_recipient_id = :id or c_recipient2_id = :id", {:id => current_user.id}])
    @found_conversations = Array.new
    received_conversations.each do |c|
      @found_conversations << c if c.search_msgs(params[:search])
      @test = search_conv(c, params[:search].to_s.downcase)
    end
  end
  
  def new
    @title = 'New conversation'
  end

  def show
    @conversation = Conversation.find(params[:id])
    @conversation.all_read(current_user)
  end

  def create
    if !params[:send].nil?
      recipient = User.find_by_name(params[:recipient])
      if recipient.nil?
        flash.now[:error] = 'User not found'
        @title = 'New conversation'
        render 'new'
      else
        @conversation = Conversation.new( :c_sender_id => current_user.id,
                                          :c_recipient_id => recipient.id,
                                          :c_recipient2_id => nil,
                                          :subject => params[:subject],
                                          :c_sender_del => false,
                                          :c_recipient_del => false)
        if @conversation.save and @conversation.create_msg(params[:content], current_user)
          UserMailer.msg_notice(recipient).deliver
          flash[:sucess] = 'Conversation started!'
          redirect_to inbox_conversations_path
        else
          flash.now[:error] = 'Sorry, there was a problem.  Please try again.'
          @title = 'New conversation'
          render 'new'
        end
      end
    end
    if !params[:cancel].nil?
      flash[:notice] = 'Message canceled'
      redirect_to inbox_conversations_path 
    end
  end
  
  def destroy
    conversation = Conversation.find(params[:id])
    if conversation.c_sender == current_user 
      if conversation.update_attributes(:c_sender_del => true)
        flash.now[:notice] = 'Conversation deleted'
      else
        flash.now[:error] = 'Sorry, there was a problem.  Please try again'
      end
    end
    if conversation.c_recipient == current_user
      if conversation.update_attributes(:c_recipient_del => true)
        flash.now[:notice] = 'Conversation deleted'
      else
        flash.now[:error] = 'Sorry, there was a problem.  Please try again'
      end
    end
    if conversation.c_sender_del and conversation.c_recipient_del
      if conversation.destroy
        flash.now[:notice] = 'Conversation deleted'
      else
        flash.now[:error] = 'Sorry, there was a problem.  Please try again.'
      end
    end
    if params[:folder] == 'sent'
      @conversations = current_user.sent_conversations
      @conv_partial = 'sent_conversations'
    else
      @conversations = get_received
      @conv_partial = 'received_conversations'
    end
    @conversations.each do |c|
      c.update_count(current_user)
    end
    respond_to do |format|
      format.html { render inbox_conversations_path } #need to add extra inbox function calls later
      format.js
    end   
  end
  
  def inbox
    @title = 'Inbox'
    @received_conversations = get_received
    @received_conversations.each do |c|
      c.update_count(current_user)
    end    
  end

  def sent
    @title = 'Sent'
    @sent_conversations = current_user.sent_conversations
  end
  
  def reply
    @conv = Conversation.find(params[:id])
    msg = Msg.new( :conversation_id => params[:id],
                    :content => params[:content],
                    :sender_id => current_user.id,
                    :c_sender_read => false,
                    :c_recip_read => false)
    if msg.save
      if current_user == @conv.c_recipient
        @conv.update_attributes(:c_sender_del => false) if @conv.c_sender_del
        @conv.update_attributes(:c_recipient2_id => @conv.c_sender_id) if @conv.c_recipient2_id.nil?
        msg.update_attributes(:c_recip_read => true)
        UserMailer.msg_notice(@conv.c_sender).deliver
      end
      if current_user == @conv.c_sender
        @conv.update_attributes(:c_recipient_del => false) if @conv.c_recipient_del
        msg.update_attributes(:c_sender_read => true)
        UserMailer.msg_notice(@conv.c_recipient).deliver
      end
      flash[:success] = 'Reply sent!'
    else
      flash[:error] = 'Sorry, there was a problem.  Please try again'
    end
    @conv.all_read(current_user)
    respond_to do |format|
      format.html { redirect_to @conv }
      format.js
    end
   end
    
  private
  
    def get_received
      Conversation.find(:all, :conditions => 
      ["c_recipient_id = :id or c_recipient2_id = :id", {:id => current_user.id}])
    end
    
    def search_conv(conversation, search)
      if search
        conversation.msgs.each do |msg|
          return true if !msg.content.downcase.match(search).nil?
        end
      end
      return false
    end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<%= conversation.msgs.last.sender.name %>
<%= link_to conversation.subject, conversation %>
<%= link_to 'Delete', conversation_path(conversation.id), :method => 'delete' %>

app/views/conversations/_received_conversations.html.erb
<% if conversations.empty? %>
	<p>You have no messages in your inbox</p>
<% else %>
	<% conversations.each do |c| %>
		<% if 	((current_user == c.c_recipient) & !c.c_recipient_del) ||
		 		((current_user == c.c_sender) & !c.c_sender_del) %>
			<%= image_tag c.msgs.first.sender.photo.url(:thumb) %>
			<%= link_to c.msgs.last.sender.name, c.msgs.last.sender %>
			<% if c.count > 0 %>
				<b><%= link_to c.subject, c %></b>
			<% else %>
				<%= link_to c.subject, c %>
			<% end %>
			<small style="color:grey"><%= c.msgs.first.content[0,30] %></small>
			<% if c.count > 0 %>
				<b>[<%= c.count %>]</b>
			<% end %>
			<%= form_tag conversation_path(c.id), :method => 'delete', :remote => true do %>
				<%= hidden_field_tag 'folder', 'inbox' %>
				<%= submit_tag 'Delete', :name => nil, :confirm => 'Are you sure?' %>
			<% end %>
		<% end %>
	<% end %>
<% end %>

app/views/conversations/_search.html.erb
<%= form_tag conversations_path, :method => 'get' do %>
	<p>
		<%= text_field_tag :search, params[:search], :placeholder => 'Search inbox' %>
		<%= submit_tag "Go!", :name => nil %><br />
	</p>
<% end %>

app/views/conversations/_sent_conversations.html.erb
<% if conversations.empty? %>
	<p>You haven't sent any messages</p>
	<%= link_to 'Start now!', new_conversation_path %>
<% else %>
	<% conversations.each do |c| %>
		<% if (current_user == c.c_sender) & !c.c_sender_del %>
			<%= image_tag c.msgs.last.sender.photo.url(:thumb) %>
			<%= link_to c.msgs.last.sender.name, c.msgs.last.sender %>
			<% if c.count > 0 %>
				<b><%= link_to c.subject, c %></b>
			<% else %>
				<%= link_to c.subject, c %>
			<% end %>
			<small style="color:grey"><%= c.msgs.first.content[0,30] %></small>
			<% if c.count > 0 %>
				<b>[<%= c.count %>]</b>
			<% end %>
			<%= form_tag conversation_path(c.id), :method => 'delete', :remote => true do %>
				<%= hidden_field_tag 'folder', 'sent' %>
				<%= submit_tag 'Delete', :name => nil, :confirm => 'Are you sure?' %>
			<% end %>
		<% end %>
	<% end %>
<% end %>

app/views/conversations/destroy.js.erb
$("conversations").update("<%= escape_javascript(render @conv_partial, :conversations => @conversations) %>")

app/views/conversations/inbox.html.erb
<h3>Inbox</h3>
<%= render 'search' %>
<%= link_to 'New Conversation', new_conversation_path %><br />
<%= link_to 'Sent', sent_conversations_path %><br />
<div id='conversations'>
	<%= render 'received_conversations', :conversations => @received_conversations %>
</div>

app/views/conversations/index.html.erb
<% if @found_conversations.empty? %>
	<p>No conversations found with search term <%= params[:search].to_s %>.</p>
<% else %>
	<%= render @found_conversations %>
<% end %>

app/views/conversations/new.html.erb
<%= form_tag conversations_path, :method => 'post' do %>
	<p>
	<%= label_tag :to %>
	<%= text_field_tag :recipient %>
	</p>
	<p>
	<%= label_tag :subject %>
	<%= text_field_tag :subject %>
	</p>
	<p>
	<%= label_tag :message %><br />
	<%= text_area_tag :content, nil, :cols => 50, :rows => 4 %>
	</p>
	<p>
	<%= submit_tag "Send message", :name => 'send' %>
	<%= submit_tag "Cancel", :name => 'cancel' %>
	</p>
<% end %>

app/views/conversations/reply.js.erb
$("show_conv").update('<%= escape_javascript(render(@conv.msgs)) %>')
$("reply_form").update('<%= text_area_tag :content, nil, :cols => 50, :rows => 4 %>')

app/views/conversations/sent.html.erb
<h3>Sent</h3>
<%= link_to 'Inbox', inbox_conversations_path %><br />
<div id='conversations'>
	<%= render 'sent_conversations', :conversations => @sent_conversations %>
</div>

app/views/conversations/show.html.erb
<%= link_to '<< Inbox', inbox_conversations_path %>
<h3><%= @conversation.subject %></h3>
<h4>Conversation between <%= @conversation.c_sender.name %> and <%= @conversation.c_recipient.name %></h4>
<div id="show_conv">
	<%= render @conversation.msgs %>
</div>
<%= form_tag reply_conversation_path, :method => 'post', :remote => true do %>
	<%= label_tag :reply %><br />
	<div id="reply_form">
	<%= text_area_tag :content, nil, :cols => 50, :rows => 4 %>
	</div>
	<%= submit_tag "Reply" %>
<% end %>