config/routes.rb
Avoberry::Application.routes.draw do

  resources :users do
    post  :reset, :on => :collection
    post  :new_post, :on => :member
    post  :comment_reply, :on => :member
    get   :show_form, :on => :member
  end
  
  resources :posts
  
  resources :friendships do
    post :create_request, :on => :collection
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :conversations do
    post :reply, :on => :member
    get :inbox, :on => :collection
    get :sent, :on => :collection
  end

  get '/contact' => 'pages#contact'
  get '/about' => 'pages#about'
  get '/help' => 'pages#help'
  get 'signup' => 'users#new'
  get '/signin' => 'sessions#new'
  get '/recover' => 'pages#recover'
  
  delete '/signout' => 'sessions#destroy'
  
  root :to => 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation, :photo, :invitaiton_token, :change_password
  
  has_attached_file :photo, :styles => { :small => "150x150>", :thumb => "75x75>", :tiny => "35x35>" } #,
                    #:url => "/:attachment/:id/:style/:basename.:extension",
                    #:path => ":rails_root/public/:attachment/:id/:style:basename.:extension"
  
  #posts
  has_many :received_posts, :class_name => 'Post', :foreign_key => 'user_id'
  has_many :sent_posts, :class_name => 'Post', :foreign_key => 'poster_id'
                    
  #validations
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,      :presence => true, 
                        :length => { :maximum => 50 }
  validates :email,     :presence => true, 
                        :format => { :with => email_regex },
                        :uniqueness => { :case_sensitive => false }
  validates :password,  :presence => true,
                        :confirmation => true,
                        :length => { :within => 6..40 }
                        
  #validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 1.megabyte
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png', 'image/gif']
  
  before_create :encrypt_password
  
  #conversations
  has_many :sent_conversations, :class_name => 'Conversation', :foreign_key => 'c_sender_id'
  #has_many :received_conversations, :class_name => 'Conversation', :foreign_key => 'c_recipient_id'
  #has_many :received_back_conversations, :class_name => 'Conversation', :foreign_key => 'c_recipient2_id'
  
  #friendships
  has_many :friendships, :dependent => :destroy
  has_many :friends, :through => :friendships
  
  #friend requests
  has_many :sent_requests, :class_name => 'Request', :foreign_key => 'sender_id'
  has_many :received_requests, :class_name => 'Request', :foreign_key => 'recipient_id'
  
  def has_password?(submitted_password)
     encrypted_password == encrypt(submitted_password)
   end

   def self.authenticate(email, submitted_password)
     user = find_by_email(email)
     return nil if user.nil?
     return user if user.has_password?(submitted_password)
   end

   def self.authenticate_with_salt(id, cookie_salt)
     user = find_by_id(id)
     return nil if user.nil?
     return user if user.salt == cookie_salt
   end
   
   def self.search(search)
     if search
       find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
      end
    end
   
   def reset_password
     random_pw = put_password(Digest::SHA1.hexdigest([Time.now, rand].join)[0,8])
     (self.change_password = true) if random_pw
     if save
       return random_pw
     else
       return false
     end
   end
   
   def put_password(pw)
     self.password = pw
     self.encrypted_password = encrypt(password)
     if save
       return password 
     else
       return false
     end
   end
   
   #friend feed
   
   def post_feed
     Post.from_users_friends_with(self)
   end
   
   #friendship procedures
   def friend?(friend)
     friendships.find_by_friend_id(friend)
   end

   def friend!(friend, request)
     friendships.create!(:friend_id => friend.id, :request_id => request.id) 
   end

   def unfriend!(friend)
     friendships.find_by_friend_id(friend).destroy
   end

   #request procedures

   def request?(friend)
     Request.find(:all, :conditions => ["sender_id = ? and recipient_id = ?", id, friend.id])
   end

   def self.search(search)
     if search
       find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
     end
   end
   
   private
   
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end
   
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
   
    def make_salt 
      secure_hash("#{Time.now.utc}--#{password}")
    end
   
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end 
     
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate, :only => [:edit, :update, :index]
  before_filter :correct_user, :only => [:edit, :update]
  
  def index
    @users = User.search(params[:search])
  end

  def new
    @title = 'Sign up'
    @user = User.new
    #@user = User.new(:invitation_token => params[:invitation_token])
  end

  def show
    @user = User.find_by_id(params[:id])
    @title = @user.name
    @post = current_user.sent_posts.build
    @user_posts = @user.received_posts
    @friends_feed = @user.post_feed  
    #@feed_assignments = @user.assignment_feed
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      UserMailer.registration_confirmation(@user).deliver
      flash[:success] = 'Welcome to Project Avocado!'
      sign_in @user, '0'
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @title = "Edit your profile"
  end
  
  def update
    @user = User.find(params[:id])
    if @user.has_password?(params[:old_password])
      if @user.update_attributes( :name => params[:name], 
                                  :email => params[:email],
                                  :password => params[:password],
                                  :password_confirmation => params[:password_confirmation])
        if @user.put_password(params[:password])
          if @user.change_password
            @user.update_attributes(:change_password => false)
          end
        end
        flash[:success] = "Profile updated"
        redirect_to @user
      else
        @title = "Edit your profile"
        render 'edit'
      end
    else 
      flash.now[:error] = "Invalid email/password combination"
      @title = "Edit your profile"
      render 'edit'
    end
  end  
  
  def reset
    @user = User.find_by_email(params[:email])
    if @user and User.find_by_name(params[:name])
      if password = @user.reset_password        
        UserMailer.reset_password(@user, password).deliver
        flash[:notice] = 'A temporary password has been sent to your email address' 
        redirect_to signin_path
      else
        flash[:error] = "Sorry, there was a problem.  Please try again"
        redirect_to recover_path
      end
    else
      flash[:error] = "Invalid email/name combination"
      redirect_to recover_path
    end
  end
  
  def new_post
    @user = User.find(params[:post][:user_id])
    new_post = current_user.sent_posts.build(params[:post])
    if new_post.save
      if !current_user?(@user)
        UserMailer.post_notice(@user, current_user).deliver
      end
      flash[:success] = 'Post created!'
    else
      flash[:error] = 'Sorry, there was a problem.  Please try again.'
      redirect_to root_path
    end
    @user_posts = @user.received_posts
    @post = Post.new
    respond_to do |format|
      format.html { redirect_to @user }
      format.js  
    end
  end
  
  def show_form
    @post_id = params[:post_id].to_s
    respond_to do |format|
      format.html { redirect_to current_user }  #need to take care of html request
      format.js
    end
   end
  
  def comment_reply
    if params[:real_commit] == 'comment' #handle reply request
      @post = Post.find(params[:post_id])
      @comment = @post.comments.build(:content => params[:content], :poster_id => current_user.id)
      if @comment.save
        flash.now[:success] = 'Comment saved!'
      else
        flash.now[:error] = 'There was a problem.  Please try again'
        redirect_to user_path(params[:id])
      end
    end
    @user_posts = User.find(params[:id]).received_posts
    respond_to do |format|
      format.html { redirect_to current_user } #need to take care of html request
      format.js
    end
  end
  
  private 
  
    def correct_user
      @user = User.find(params[:id])
      if !current_user?(@user)
        flash[:error] = 'You do not have permission to access this page'
        redirect_to root_path
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_comment_reply_form.html.erb
<%= form_tag comment_reply_user_path, :method => 'post', :id => 'myform', :remote => true do %>
	<%= label_tag :reply %><br />
	<%= hidden_field_tag :post_id, @post_id %>
	<%= hidden_field_tag "real_commit", "" %>
	<%= text_area_tag :content, nil, :cols => 50, :rows => 1 %>
	<%= submit_tag "comment", :onclick => "$('real_commit').value='comment';" %>
	<%= submit_tag "cancel", :onclick => "$('real_commit').value='cancel';" %>
	<%-# button_to_function "Comment", "$('real_commit').value='comment';$('myform').submit();" %>
	<%-# button_to_function "Cancel", "$('real_commit').value='cancel';$('myform').submit();" %>
<% end %>

app/views/users/_my_friends.html.erb
<% user.friends.each do |f| %>
	<% avatar = image_tag f.photo.url(:tiny) %>
	<%= link_to avatar, f %><br />
<% end %>

app/views/users/_post_form.html.erb
<%= form_for @post, :url => new_post_user_path, :method => 'post', :remote => true do |f| %>
	<%= @post.content = nil %>
	<%= f.hidden_field :user_id, :value => user_id %>
	<%= f.label :new_post %><br />
	<%= f.text_area :content, :cols => 30, :rows => 4 %><br />
	<%= f.submit 'Submit' %>
<% end %>

app/views/users/_show_comment_form.html.erb
<%= form_tag show_form_user_path, :method => 'get', :remote => true do %>
	<%= hidden_field_tag :post_id, post_id %>
	<%= submit_tag "Add comment" %>
<% end %>

app/views/users/_user.html.erb
<%= image_tag user.photo.url(:thumb) %>
<%= link_to user.name, user %> <br />

app/views/users/_user_search.html.erb
<%= form_tag users_path, :method => 'get' do %>
	<p>
		<%= text_field_tag :search, params[:search], :placeholder => 'Find a friend!' %>
		<%= submit_tag "Go!", :name => nil %><br />
	</p>
<% end %>

app/views/users/comment.js.erb
$("posts").update('<%= escape_javascript(render(@user_posts)) %>')
$("post_partial").update("<%= escape_javascript(render('post_form', :user_id => @user.id)) %>")

app/views/users/comment_cancel.js.erb
$("posts").update("<%= escape_javascript(render(@user_posts)) %>")

app/views/users/comment_reply.js.erb
$("posts").update("<%= escape_javascript(render(@user_posts)) %>")

app/views/users/edit.html.erb
<h3>Edit your profile</h3>

<%= form_tag user_path(current_user), :method => 'put', :html => { :multipart => true } do %>
	<%= render 'shared/error_messages', :object => current_user %>
	<div class="field">
		<%= label_tag :name %><br />
		<%= text_field_tag :name %>
	</div>
	<div class="field">
		<%= label_tag :email %><br />
		<%= text_field_tag :email %>
	</div>
	<div class="field">
		<%= label_tag :old_password %><br />
		<%= password_field_tag :old_password %>
	</div>
	<br />
	<div class="field">
		<%= label_tag :new_password %><br />
		<%= password_field_tag :password %>
	</div>
	<br />
	<div class="field">
		<%= label_tag :confirm_password %><br />
		<%= password_field_tag :password_confirmation %>
	</div>
	<br />
	<div class="field">
		<%= label_tag :photo, "Profile picture" %>
		<%= file_field_tag :photo %>
	</div>
	<br />
	<div class="actions">
		<%= submit_tag "Update" %>
	</div>
<% end %>

app/views/users/index.html.erb
<% if @users.empty? %>
	<p>No users found.  Tell a friend!</p>
<% else %>
	<%= render @users %>
<% end %>

app/views/users/new.html.erb
<h3>Sign up</h3>

<%= form_for @user, :html => { :multipart => true } do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<%-# f.hidden_field :invitation_token %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name, :placeholder => 'Your full name' %>
	</div>
	<div class="field">
	    <%= f.label :email %><br />
	    <%= f.text_field :email, :placeholder => 'Your unique email address' %>
	</div>
	<div class="field">
	    <%= f.label :password %><br />
	    <%= f.password_field :password, :placeholder => 'At least 6 characters long' %>
	</div>
	<div class="field">
	    <%= f.label :password_confirmation, "Confirmation" %><br />
	    <%= f.password_field :password_confirmation, :placeholder => 'Enter password again' %>
	</div>
	<br />
	<div class="field">
		<%= f.label :photo, "Profile picture" %>
		<%= f.file_field :photo %>
	</div>
		<%-# f.label :role, "I am a..." %>
		<%-# select(:user, :role, [['Student'], ['Teacher'], ['Parent']]) %>
	<br />
	<div class="actions">
	    <%= f.submit "Sign up" %>
	</div>
<% end %>

app/views/users/show.html.erb
<%= image_tag @user.photo.url(:thumb) %> <%= @user.name %>
<h3>My friends</h3>
<%= render 'my_friends', :user => @user %>
<h3>Friend feeds</h3>
<%= render @friends_feed %>
<%= render 'friend_form' %>
<%= render @user.received_requests %>
<h3>My Wall</h3>
<div id="posts">
	<%= render @user_posts %>
</div>
<div id="post_form">
	<%= render 'post_form', :user_id => @user.id %>
</div>

app/views/users/show_form.js.erb
$("<%= @post_id %>").update("<%= escape_javascript(render('comment_reply_form')) %>")