config/routes.rb
Avoberry::Application.routes.draw do

  resources :users do
    post  :reset, :on => :collection
    post  :new_post, :on => :member
    post  :comment_reply, :on => :member
    get   :show_form, :on => :member
  end
  
  resources :posts
  
  resources :friendships do
    post :create_request, :on => :collection
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :conversations do
    post :reply, :on => :member
    get :inbox, :on => :collection
    get :sent, :on => :collection
  end

  get '/contact' => 'pages#contact'
  get '/about' => 'pages#about'
  get '/help' => 'pages#help'
  get 'signup' => 'users#new'
  get '/signin' => 'sessions#new'
  get '/recover' => 'pages#recover'
  
  delete '/signout' => 'sessions#destroy'
  
  root :to => 'pages#home'

end

app/views/pages/about.html.erb
<h3>About the project</h3>
<p>Project Avocado v1.0. BETA was started 3/30/11 to mimic a simplified version of the Facebook messaging system.  The purpose is to practice programming in RoR.</p>

app/views/pages/contact.html.erb
<h3>Contact</h3>
<p>Please report all bugs to <%= mail_to "rluavocado@gmail.com" %></p>

app/views/pages/help.html.erb
<h3>Help</h3>
<p>Nothing here</p>

app/views/pages/home.html.erb
<p>Project Avocado v1.0.  BETA release of simple messaging system.</p>
<% if signed_in? %>
	<p>Only site functionality so far is the inbox.  Try it out!</p>
	<%= link_to "Inbox", inbox_conversations_path %>
<% else %>
	<%= link_to "Sign up!", signup_path %>
<% end %>

app/views/pages/recover.html.erb
<h3>Identify Your Account</h3>
<p>Please fill in the following information to verify your account</p>
<%= form_tag reset_users_path, :method => 'post' do %>
	<p>
	<%= label_tag :email %>
	<%= text_field_tag :email, nil, :placeholder => 'a@b.com' %>
	</p>
	<p>
	<%= label_tag :name %>
	<%= text_field_tag :name, nil, :placeholder => 'John Smith' %>
	</p>
	<p>
	<%= submit_tag 'Reset password' %>
	</p>
<% end %>
		