config/routes.rb
Avoberry::Application.routes.draw do

  resources :users do
    post  :reset, :on => :collection
    post  :new_post, :on => :member
    post  :comment_reply, :on => :member
    get   :show_form, :on => :member
  end
  
  resources :posts
  
  resources :friendships do
    post :create_request, :on => :collection
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :conversations do
    post :reply, :on => :member
    get :inbox, :on => :collection
    get :sent, :on => :collection
  end

  get '/contact' => 'pages#contact'
  get '/about' => 'pages#about'
  get '/help' => 'pages#help'
  get 'signup' => 'users#new'
  get '/signin' => 'sessions#new'
  get '/recover' => 'pages#recover'
  
  delete '/signout' => 'sessions#destroy'
  
  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<ul>
	<li><%= link_to 'About', about_path %></li>
	<li><%= link_to 'Contact', contact_path %></li>
	<li><%= link_to 'Help', help_path %></li>
</ul>

app/views/layouts/_header.html.erb
<% if !signed_in? %>
	<% if !(@title == 'Sign in') %>
		<%= form_for(:session, :url => sessions_path) do |f| %>
			<%= f.label :email %>
			<%= f.text_field :email, :size => 15 %>
			<%= f.label :password %>
			<%= f.password_field :password, :size => 15 %>
			<%= f.submit "Sign in" %><br />
			<%= f.label :Remember_me %>
			<%= f.check_box :permanent %>
			<li><%= link_to "Forgot your password?", recover_path %>
		<% end %>
	<% end %>
<% end %>
<ul>
	<li><%= link_to "Home", root_path %></li>
	<% if signed_in? %>
		<li><%= link_to "Settings", edit_user_path(current_user) %></li>
		<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
		<li>Signed in as <%=link_to current_user.name, current_user %></li><br />
		<%= render '/users/user_search' %>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title><%= title %></title>
  		<%= stylesheet_link_tag :all %>
  		<%= javascript_include_tag :defaults %>
  		<%= csrf_meta_tag %>
	</head>
	<body>
		<header>
		<%= render 'layouts/header' %>
		</header>
		<section>
			<% flash.each do |key, value| %>
				<%= value %>
			<% end %>
			<%= yield %>
		</section>
		<footer>
			<%= render 'layouts/footer' %>
		</footer>
		<%= debug(params) if Rails.env.development? %>
	</body>
</html>